// 14 Javascript Frameworks/2_Angular/my-app/src/app/app.component.ts
import { Component } from '@angular/core';

type Movie = {
  name: String,
  available: number,
  quantity: number,
};
type Movies = Array<Movie>;

@Component({
  selector: 'app-root',
  // template: `<h2>Hey!</h2>`
  templateUrl: './app.component.html',
  // styleUrls: ['./app.component.css']
})
export class AppComponent {
  title: String = 'Movies';
  movies: Movies = [
  {
      name: "Avengers",
      available: 5,
      quantity: 0,
  },
  {
    name: "Forest Gump",
    available: 2,
    quantity: 0,
  },
  ];

  addMovieQuantity (movieName: String){
    const movieIndex: number = this.movies.findIndex(
      movie => movie.name === movieName,
    );

      this.movies[movieIndex].quantity += 1;
  }

  rmvMovieQuantity (movieName: String){
    const movieIndex: number = this.movies.findIndex(
      movie => movie.name === movieName,
    );

      this.movies[movieIndex].quantity -= 1;
  }
}

<h2>{{ title }}</h2>

<div>
  <form *ngFor="let movie of movies">
    <h3>{{movie.name}}</h3>

    <button 
      type="button"
      (click)="rmvMovieQuantity(movie.name)"
      [disabled]="movie.quantity <= 0"
      > - </button>
    {{ movie.quantity }}
    <button 
      type="button"
      (click)="addMovieQuantity(movie.name)"
      [disabled]="movie.quantity >= movie.available"
      > + </button>

  </form>
</div>

// 14 Javascript Frameworks/1_React/my-app/src/App.js
import logo from './logo.svg';
import form from './form'
import Form from './form';

const movies = [
  {
    name: 'Avengers',
    available: 5,
  },
  {
    name: "Forest Gump",
    available: 6
  }
];


function App() {
  return (
    <div className="App-header">
      <header> <h2>Movies</h2> </header>

      {movies.map( movie => (

        <Form movie={movie}/>

      ))}

    </div>

  );
}

export default App;
